APP_NAME="smw"
APP_TITLE="SuperMarioWar"
APP_AUTHOR="ported by p-sam"
APP_SEMVER="2.0.0"
APP_VERSION_SUFFIX="nx4"
APP_VERSION="$APP_SEMVER-$APP_VERSION_SUFFIX"

SMW_DATA_REPO="mmatyas/supermariowar-data"
SMW_DATA_VERSION="bfcf8903aa56fa57d894dcee7aae86b301748fb7"